IINSERT INTO `categorias` (`idcategorias`, `nombreCategoría`, `rangoMin`, `rangoMax`, `descripcionCategoria`) VALUES (NULL, 'Pre-Infantil Masculino - 10K', '12', '15', 'Pre-Infantil masculino'),
(NULL, 'Pre-Infantil Femenino - 10K', '12', '15', 'Pre-Infantil femenino'),
(NULL, 'Pre-Infantil Masculino - 21K', '12', '15', 'Pre-Infantil masculino'),
(NULL, 'Pre-Infantil Femenino - 21K', '12', '15', 'Pre-Infantil femenino'),
(NULL, 'Pre-Infantil Masculino - 30K', '12', '15', 'Pre-Infantil masculino'),
(NULL, 'Pre-Infantil Femenino - 30K', '12', '15', 'Pre-Infantil femenino'),

(NULL, 'Pre-Juvenil Masculino - 10K', '15', '18', 'Pre-Juvenil masculino'),
(NULL, 'Pre-Juvenil Femenino - 10K', '15', '18', 'Pre-Juvenil femenino'),
(NULL, 'Pre-Juvenil Masculino - 210K', '15', '18', 'Pre-Juvenil masculino'),
(NULL, 'Pre-Juvenil Femenino - 21K', '15', '18', 'Pre-Juvenil femenino'),
(NULL, 'Pre-Juvenil Masculino - 30K', '15', '18', 'Pre-Juvenil masculino'),
(NULL, 'Pre-Juvenil Femenino - 30K', '15', '18', 'Pre-Juvenil femenino'),

(NULL, 'General Masculino - 10K', '18', '40', 'General masculino'),
(NULL, 'General Femenino - 10K', '18', '40', 'General femenino'),
(NULL, 'General Masculino - 21K', '18', '40', 'General masculino'),
(NULL, 'General Femenino - 21K', '18', '40', 'General femenino'),
(NULL, 'General Masculino - 30K', '18', '40', 'General masculino'),
(NULL, 'General Femenino - 30K', '18', '40', 'General femenino'),

(NULL, 'Master-A Masculino - 10K', '40', '50', 'Master-A masculino'),
(NULL, 'Master-A Femenino - 10K', '40', '50', 'Master-A femenino'),
(NULL, 'Master-A Masculino - 21K', '40', '50', 'Master-A masculino'),
(NULL, 'Master-A Femenino - 21K', '40', '50', 'Master-A femenino'),
(NULL, 'Master-A Masculino - 30K', '40', '50', 'Master-A masculino'),
(NULL, 'Master-A Femenino - 30K', '40', '50', 'Master-A femenino'),

(NULL, 'Master-B Masculino - 10K', '50', '100', 'Master-B masculino'),
(NULL, 'Master-B Femenino - 10K', '50', '100', 'Master-B femenino'),
(NULL, 'Master-B Masculino - 21K', '50', '100', 'Master-B masculino'),
(NULL, 'Master-B Femenino - 21K', '50', '100', 'Master-B femenino'),
(NULL, 'Master-B Masculino - 30K', '50', '100', 'Master-B masculino'),
(NULL, 'Master-B Femenino - 30K', '50', '100', 'Master-B femenino')